version: "3.8"

services:
  trading-system:
    build: .
    container_name: trading-bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Madrid
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Simple web dashboard
  web-dashboard:
    build: .
    container_name: trading-dashboard
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      - FLASK_ENV=production
    command: python web_dashboard.py
    depends_on:
      - trading-system
